name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '5.6'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none

      - name: Install Dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run Tests
        run: composer run test
